apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-federation
  namespace: cattle-monitoring-system
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: prometheus-cluster.bbtech.io.vn   # change to your domain or external IP
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rancher-monitoring-prometheus
                port:
                  number: 9090
  tls:
    - hosts:
        - prometheus-cluster.bbtech.io.vn
      secretName: bbtech-tls